### PR TITLE
use custom names for custom subnets

### PR DESCRIPTION
**Pull request by aryszka**
Signed-off-by: Arpad Ryszka <arpad.ryszka@gmail.com>

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
LGTM, although I'd consider what happens if someone runs an older version of 7s. Would the subnet be deleted/tags broken?
You might want to bump the [minimum config version](https://github.com/zalando-stups/sevenseconds/blob/509364d339b2eaa794ef6e4464b5d45ab2b83e1f/sevenseconds/cli.py#L17) just in case.

**Comment by aryszka** [comment]
:+1:

**Comment by elgalu** [comment]
:+1:

**Comment by elgalu** [comment]
👍🏽

**Comment by aryszka** [comment]
:+1:

**Comment by jonathanbeber** [comment]
:+1:

**Pull request merged**
