### PR TITLE
Enhance S3 Bucket Creation

### PR DESCRIPTION
**Pull request by christianberg**
This PR allows to configure the following attributes for the created S3 buckets:
- Lifecycle rules for any S3 bucket (not just logging target buckets)
- Server-side encryption rules
- Tagging

### CODE REVIEW

**Comment by szuecs** [comment]
@christianberg please fix the travis errors, thanks

Code looks ok to me

**Comment by christianberg** [comment]
I'm sorry, I don't really understand this. I tried upgrading pytest, and now the build of the branch on Travis-CI passes, but the build of the PR fails.

Since the build was broken before my PR, maybe one of you can take a look?

**Comment by mikkeloscar** [comment]
@christianberg I'm having a look to fix it!

**Comment by mikkeloscar** [comment]
I'm just upgrading the version of python and then it works: https://github.com/zalando-stups/sevenseconds/pull/83 please rebase on master when this is merged!

**Comment by mikkeloscar** [comment]
@christianberg I rebased your PR on master, should work now!

**Comment by christianberg** [comment]
Thank you @mikkeloscar!

**Comment by christianberg** [comment]
I changed the scope of the PR and added more functionality (see updated title and description above).

**Comment by njuettner** [comment]
👍

**Comment by gargravarr** [comment]
:+1:

**Pull request merged**
