### PR TITLE
Allow opting out of DNS management

### PR DESCRIPTION
**Pull request by aermakov-zalando**
If `account.domain` is set to `null`, don't manage DNS for account. This will not create DNS records for NAT GWs, the bastion host, or try to manage the certificate.

I tried improving the typing situation a bit (using proper types instead of `account: object` everywhere), which unfortunately necessitated moving stuff around to avoid circular imports. I didn't do a really good job at it, but I don't think this codebase can be improved incrementally.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Do I understand correctly that we need to specify the domain for all accounts now? Or do we just need to set `domain: null` to opt out? In our big configuration file I mean.

**Comment by aermakov-zalando** [comment]
@mikkeloscar no, it's inherited from the default configuration, we just opt out for individual accounts.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
Found a bug for accounts with no opt out, please +1 again!

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
